###
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "nombre": "Joaquin",
    "apellido": "Fiorio",
    "pais": "Argentina",
    "ciudad": "pergamino",
    "telefono": 2477358701,
    "direccion": "dorrego 630",
    "email": "joaquin.fiorio12@hotmail.com",
    "direccion":"dorrego 620",
    "password": 12345
}

###
POST http://localhost:3000/api/user/signin
Content-Type: application/json

{
    "email": "joaquin.fiorio1@hotmail.com",
    "password": "12345"
}

###
PUT http://localhost:3000/api/user/user/64a5cf11a613bcdbd397c4d5
Content-Type: application/json

{
    "nombre": "Joaquin",
    "apellido": "Fiorio",
    "pais": "Argentina",
    "ciudad": "pergamino",
    "telefono": 2477358701,
    "direccion": "dorrego 630"
}

###
POST http://localhost:3000/api/pedidos
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjE5ODZkZTM2YWM0Mjc3NTkyZTEwOSIsImlhdCI6MTY4OTM2MDQ5NiwiZXhwIjoxNjg5NDQ2ODk2fQ.O7lgHUnEcpljXaTYRamCPbwJrT6pcoyLv9crblpFXNk

{
    "producto": {
        "nombre": "Joaquin",
        "precio": "Fiorio",
        "categoria": "Argentina",
        "descripcion": "Joaquin"
    },
    "precio": 12,
    "infoUsuario": {
        "nombre": "Joaquin",
        "apellido": "Fiorio",
        "pais": "Argentina",
        "ciudad": "pergamino",
        "telefono": 2477358701,
        "direccion": "dorrego 630"
    }
}

###
DELETE http://localhost:3000/api/pedidos/eliminar
Content-Type: application/json

{
    "id": "29b8cd80-2335-11ee-884f-47215a29c3ce",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjJkNzNjMmY0YmJiMjM5OGE2M2Q1MCIsImlhdCI6MTY4OTQ0MjE0NiwiZXhwIjoxNjg5NTI4NTQ2fQ.5T0vA5UKnM4_OViWWzkiFjtbCpdcC0gnpVO3ML9-1Go"
}

###
GET http://localhost:3000/api/pedidos
Content-Type: application/json

###
POST http://localhost:3000/api/pagar/createOrder
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjJkNzNjMmY0YmJiMjM5OGE2M2Q1MCIsImlhdCI6MTY5MTY4NDIxOCwiZXhwIjoxNjkxNzcwNjE4fQ.5XBvtroLXaPgzuAZherPB26zthgX0L3_6ss3YiwjnxM

{
    "producto": {
        "_id": "64d50f385eb25f0027c2d8eb",
        "title": "Jarron beige",
        "description": "jarron lindo",
        "precio": "120",
        "categoria": "Jarrones",
        "imagePath": "uploads/39a9a946-a534-41b6-8daf-31b0f2872d16.jpeg",
        "descuento": 0,
        "estado": ""
    },
    "precio": 12,
    "infoUsuario": {
        "nombre": "Joaquin",
        "apellido": "Fiorio",
        "pais": "Argentina",
        "ciudad": "pergamino",
        "telefono": 2477358701,
        "direccion": "dorrego 630"
    }
}

